### ISSUE TITLE
Transmux videos in persistent volumes

### ISSUE THREAD

**Issue by zcesur** [algora-io/tv#18]
```bash
fly volume create algora_media_tmp --size 20 --region lax
```

```toml
[mounts]
  source="algora_media_tmp"
  destination="/data"
```

- can we add volume to FLAME worker?
- otherwise can we add volume to primary node only?
